# Generated by Django 3.0 on 2021-03-11 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210309_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('fk_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Paciente')),
                ('fk_patologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Patologia')),
            ],
        ),
        migrations.CreateModel(
            name='SintomasPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Informe')),
                ('fk_sintoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Sintoma')),
            ],
        ),
    ]
