# Generated by Django 3.0 on 2021-03-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_informe_sintomaspaciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='fk_patologia',
        ),
        migrations.AddField(
            model_name='informe',
            name='patologias',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
