# Generated by Django 3.0 on 2021-03-11 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210311_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleInforme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='informe',
            name='patologias',
        ),
        migrations.DeleteModel(
            name='SintomasPaciente',
        ),
        migrations.AddField(
            model_name='detalleinforme',
            name='fk_informe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Informe'),
        ),
        migrations.AddField(
            model_name='detalleinforme',
            name='fk_patologia',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Patologia'),
        ),
        migrations.AddField(
            model_name='detalleinforme',
            name='fk_sintoma',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Sintoma'),
        ),
    ]
