# Generated by Django 3.0 on 2021-03-12 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210311_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleinforme',
            name='fk_patologia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Patologia'),
        ),
    ]
