# Generated by Django 3.0 on 2021-03-13 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210312_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleinforme',
            name='fk_sintoma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Sintoma'),
        ),
    ]
