# Generated by Django 3.0 on 2021-03-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210313_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleinforme',
            name='fk_patologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Patologia'),
        ),
        migrations.AlterField(
            model_name='detalleinforme',
            name='fk_sintoma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Sintoma'),
        ),
    ]
