# Generated by Django 3.0 on 2021-03-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_paciente_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patologia',
            name='valor_adicional',
        ),
        migrations.RemoveField(
            model_name='sintoma',
            name='valor_adicional',
        ),
        migrations.AddField(
            model_name='patologia',
            name='dato_adicional',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sintoma',
            name='dato_adicional',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
